version: "3"

services:

  test-setup:
    image: swiftly:amazonlinux2-test
    build:
      context: ..
      dockerfile: docker/test-amazonlinux2.dockerfile
      args:
        base_image: "swift:5.10-amazonlinux2"

  test:
    image: swiftly:amazonlinux2-test

  install-test-setup:
    image: swiftly:amazonlinux2-install-test
    build:
      context: ..
      dockerfile: docker/install-test-amazonlinux2.dockerfile
      args:
        base_image: "amazonlinux:2"

  install-test:
    image: swiftly:amazonlinux2-install-test

  shell:
    image: swiftly:amazonlinux2-test
