version: "3"

services:

  test-setup:
    image: swiftly:20.04-test
    build:
      args:
        base_image: "swift:5.10-focal"

  test:
    image: swiftly:20.04-test

  install-test-setup:
    image: swiftly:20.04-install-test
    build:
      args:
        base_image: "ubuntu:focal"

  install-test:
    image: swiftly:20.04-install-test

  shell:
    image: swiftly:20.04-test
