version: "3"

services:

  test-setup:
    image: swiftly:22.04-test
    build:
      args:
        base_image: "swift:5.10-jammy"

  test:
    image: swiftly:22.04-test

  install-test-setup:
    image: swiftly:22.04-install-test
    build:
      args:
        base_image: "ubuntu:jammy"

  install-test:
    image: swiftly:22.04-install-test

  shell:
    image: swiftly:22.04-test
