version: "3"

services:

  test-setup:
    image: swiftly:ubi9-test
    build:
      context: ..
      dockerfile: docker/test-ubi9.dockerfile
      args:
        base_image: "swift:5.10-rhel-ubi9"

  test:
    image: swiftly:ubi9-test

  install-test-setup:
    image: swiftly:ubi9-install-test
    build:
      context: ..
      dockerfile: docker/install-test-ubi9.dockerfile
      args:
        base_image: "redhat/ubi9:latest"

  install-test:
    image: swiftly:ubi9-install-test

  shell:
    image: swiftly:ubi9-test
