version: "3"

services:

  test-setup:
    image: swiftly:18.04-test
    build:
      args:
        base_image: "swift:5.10-bionic"

  test:
    image: swiftly:18.04-test

  install-test-setup:
    image: swiftly:18.04-install-test
    build:
      args:
        base_image: "ubuntu:bionic"

  install-test:
    image: swiftly:18.04-install-test

  shell:
    image: swiftly:18.04-test
