name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of swiftly to build release artifacts"
        required: true
        type: string
        default: "0.4.0-dev"
      skip:
        description: "Perform release checks, such as the git tag, and swift version, or '--skip' to skip that."
        required: true
        type: string
        default: "--skip"

env:
  SWIFTLY_BOOTSTRAP_VERSION: 0.4.0-dev

jobs:
  buildrelease:
    name: Build Release
    runs-on: ubuntu-latest
    container:
      image: "redhat/ubi9"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare the action
        run: ./scripts/prep-gh-action.sh
      - name: Install swiftly
        run: bash -c 'curl -O https://download.swift.org/swiftly/linux/swiftly-${SWIFTLY_BOOTSTRAP_VERSION}-$(uname -m).tar.gz && tar zxf swiftly-*.tar.gz && ./swiftly init -y --skip-install'
      - name: Update environment
        run: bash -c '. "/root/.local/share/swiftly/env.sh" && echo "PATH=$PATH" >> "$GITHUB_ENV" && echo "SWIFTLY_HOME_DIR=$SWIFTLY_HOME_DIR" >> "$GITHUB_ENV" && echo "SWIFTLY_BIN_DIR=$SWIFTLY_BIN_DIR" >> "$GITHUB_ENV"'
      - name: Install selected swift toolchain
        run: swiftly install --post-install-file=post-install.sh
      - name: Perform swift toolchain post-installation
        run: chmod u+x post-install.sh && ./post-install.sh
      - name: Display swift version
        run: swift --version
      - name: Build Release Artifact
        run: swift run build-swiftly-release --use-rhel-ubi9 ${{ inputs.skip }} ${{ inputs.version }}
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: swiftly-release-x86_64
          path: .build/release/swiftly-*.tar.gz
          if-no-files-found: error
      - name: Build Documentation Artifacts
        run: swift package --allow-writing-to-directory .build/docs generate-documentation --target SwiftlyDocs --output-path .build/docs
      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftly-docs
          path: .build/docs/**
          if-no-files-found: error
